### PR TITLE
ACF 6 compatibility, fix #29

### LINKED ISSUE #29: Please make this plugin compatible with ACF 6.0 >
Hello,

I tried to update to ACF 6.0 but the acf-icon-picker is causing an error:

Screenshot 2022-09-26 at 14 25 54

See also:
https://github.com/AdvancedCustomFields/acf/issues/717

Thanks

### PR DESCRIPTION
**Pull request by idflood**
Hi @houke ,

I've made a very small js change to fix the compatibility issue with ACF 6.

Best regards

### CODE REVIEW

**Comment by tlewap** [comment]
Thank you

**Comment by idflood** [comment]
I can't publish this repository on composer, but maybe @klaudiomilankovic who merged the pull request can do it.

**Comment by tlewap** [comment]
@houke maybe you can add me write acces to this repo?

**Comment by klaudiomilankovic** [comment]
I've made a new release, it should be fine.

**Pull request merged**
